---

- name: Ensure required GPG keys are added (Ubuntu)
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  when: ansible_os_family == "Debian"

- name: Ensure required repositories and keys are added (Ubuntu)
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
    state: present
    filename: elasticsearch
  when: ansible_os_family == "Debian"

- name: Update apt cache (Ubuntu)
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install Elasticsearch
  package:
    name: elasticsearch
    state: present
  when: ansible_os_family == "Debian"

- name: Configure Elasticsearch
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: "^#?(network.host:)"
    line: "network.host: localhost"
  notify: restart elasticsearch

- name: Ensure Elasticsearch is started and enabled
  service:
    name: elasticsearch
    state: started
    enabled: yes
  notify: restart elasticsearch
